# Set this website's info
# Change "coffeebank" to your GitHub username
# Change "moonrise" to your repository name
# googleAnalyticsID: (uncomment to use)


# Set basic server info
serverName: Dreamland
serverDescription: A Minecraft server where we have lots of fun!
serverIP: dreamland_smp_69:18269
useBedrockForOnlineStatus: false


# Discord information


# Don't change anything below here, these are defaults set by GitHub Pages:
# ======
theme: minima
# plugins:
#   - jekyll-feed
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
